---
- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Install Docker
      ansible.builtin.apt:
       name: docker.io
       state: present

    - name: Install pip3 package
      package:
        update_cache: yes 
        name: python3-pip
        state: latest

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Create Directory for projects
      file: path=/docker state=directory

    - name: Copy NGINX docker 
      copy:
        src: /docker/nginx
        dest: /docker 
        mode: 0755
        owner: root
        group: root

    - name: Build Nginx Docker container 
      community.docker.docker_image:
        build: 
          path: /docker/nginx
        name: nginx
        tag: devops
        source: build
 
    - name: Copy Flask docker 
      copy:
        src: flask
        dest: /docker/ 
        mode: 0755
        owner: root
        group: root

    - name: Build Flask Docker container 
      community.docker.docker_image:
        build: 
          path: /docker/flask
        name: flask
        tag: devops
        source: build 

    - name: Create a network
      community.docker.docker_network:
        name: network

    - name: Run Flask server 1
      docker_container:
        name: flask_srv1
        image: flask:devops
        state: started
        exposed_ports: 5000
        networks:
          - name: network

    - name: Run Flask server 2
      docker_container:
        name: flask_srv2
        image: flask:devops
        state: started
        exposed_ports: 5000
        networks:
          - name: network

    - name: Run Nginx
      docker_container:
        name: nginx
        image: nginx:devops
        state: started
        published_ports: "80:80"
        exposed_ports: 80
        networks:
          - name: network
